sudo: false
language: python
python:
- '2.7'

# These doesn't install on Travis right now!
#- '3.0'
#- '3.1'
#- '3.2'
#- '3.3'

- '3.4'
- '3.5'
- '3.6'
- '3.7'
- nightly

install:
- pip install -U pip virtualenv
script:
- if [[ $TRAVIS_PYTHON_VERSION != 2.7 && $TRAVIS_PYTHON_VERSION != 3.2 && $TRAVIS_PYTHON_VERSION != 3.3 && $TRAVIS_PYTHON_VERSION != 3.4 ]]; then make setup-venv setup-coverage test-coverage; else make test; fi
- if [[ $TRAVIS_PYTHON_VERSION > 3.4 ]]; then make setup-misc; source .venv/bin/activate; make check; fi
- if [[ $TRAVIS_PYTHON_VERSION > 3.4 ]]; then make setup-bandit; source .venv/bin/activate; make security-check; fi
after_success:
- if [[ $TRAVIS_PYTHON_VERSION != 3.2 && $TRAVIS_PYTHON_VERSION != 3.3 && $TRAVIS_PYTHON_VERSION != 3.4 ]]; then make coveralls; fi
